### ISSUE TITLE
Why my "Linux" wallet doesn't have the "xcash-daemon-rpc" command

### ISSUE THREAD

**Issue by tzdadada** [X-CASH-official/xcash-core#11]
only
`xcashd`
`xcash-wallet-cli`
`xcash-wallet-rpc`

**Comment by zachhildreth** [comment]
Hi @tzdadada 
There should only be the 3 files you write above, plus some other lesser used ones

`xcashd` is for the blockchain
`xcash-wallet-rpc` is an RPC wallet interface
`xcash-wallet-cli` is the CLI Wallet

**Comment by tzdadada** [comment]
@zachhildreth 
Thanks for your reply

**Comment by zachhildreth** [comment]
Closing this as it looks resolved
