### ISSUE TITLE
[feat] Remove unused Monero miner from xcashd (and simple_wallet/rpc commands)

### ISSUE THREAD

**Issue by ghost** [X-CASH-official/xcash-core#25]
The inherited Monero CPU miner built into the daemon source code has not been realistically usable for years and triggers Anti-Virus software when the binaries are downloaded. 

**Expected Behavior**
All traces of the Monero miner should be removed to prevent triggering an anti-virus block. With luck, removing the miner will allow users to install the wallet without any issues with the myriad of installed AV products.

**Current Behavior**
The unused Monero CPU miner code is embedded into the current xcashd binary.

**Possible Solution**
If no miner source code is used in DPOPS block creation, then the entire [miner object source code ](https://github.com/X-CASH-official/xcash-core/blob/master/src/cryptonote_basic/miner.cpp) should be removed from the project to avoid adding code that will be flagged by AV software. Any code that may be used should be migrated into a DPOPS specific object that hopefully will not trigger AV catches.

**Context**
I do not see issues in Ubuntu since AV tools are generally less intrusive on Linux desktops, but I have seen several complaints in discord from the wallets being blocked from within Windows. I would be willing to do some research to provide suggested methods to excise this code if needed.

**Comment by zachhildreth** [comment]
@CygnusMiner This is actually a really great idea! I think you mentioned it before but yes I would like a github issue on it as it reminds me and somehow gets me to do it faster lol

I think it is doable because the actual miner program is never used. I might also remove some rpc commands as well that are not used on the mining part.
