### ISSUE TITLE
[bug] annoying debug build bug

### ISSUE THREAD

**Issue by ghost** [X-CASH-official/xcash-core#27]
# 🐛 BUG REPORT 
**Expected Behavior**
The debug build command `make debug --jobs=$(nproc)` should build successfully with no changes after cloning the build tree.

**Current Behavior**
The debug build errors out at [xcash-core/src/debug_utilities/object_sizes.cpp](https://github.com/X-CASH-official/xcash-core/blob/56b8963b3ee510f114aa2cd022fa3819647f1628/src/debug_utilities/object_sizes.cpp), not recognizing 'X-CASH'. Likely a global search/replace residual.

**Possible Solution**
Lines [112-117](https://github.com/X-CASH-official/xcash-core/blob/56b8963b3ee510f114aa2cd022fa3819647f1628/src/debug_utilities/object_sizes.cpp#L112) should be changed from:
```
  SL(X-CASH::WalletImpl);
  SL(X-CASH::AddressBookRow);
  SL(X-CASH::TransactionInfoImpl);
  SL(X-CASH::TransactionHistoryImpl);
  SL(X-CASH::PendingTransactionImpl);
  SL(X-CASH::UnsignedTransactionImpl);
```

to
```
  SL(XCash::WalletImpl);
  SL(XCash::AddressBookRow);
  SL(XCash::TransactionInfoImpl);
  SL(XCash::TransactionHistoryImpl);
  SL(XCash::PendingTransactionImpl);
  SL(XCash::UnsignedTransactionImpl);
```

to match the correct XCash namespace.

**Steps to Reproduce (for bugs)**
type 'make debug'

**Context**
Having a debug build fail is annoying. :)

**Your Environment**
Ubuntu 20.04

**Comment by zachhildreth** [comment]
Thanks @CygnusMiner for finding this!

The fix provided above did work, and I will include this in the next testnet update
